Repository gismo/gismo, pull requests merged in 2025-03, with the labels that each got.

#794 Avoids exposing 'gismo' namespace in header file.
  src/gsModeling/gsBarrierPatch.h
Labels: bug

#801 Fix gsExprAssembler::computePattern
  src/gsAssembler/gsExprAssembler.h
Labels: bug, enhancement

#746 Introducing: Composite maps
  examples/compositions_example.cpp
  filedata/unittests/gsComposedBasis.xml
  filedata/unittests/gsComposedFunction.xml
  filedata/unittests/gsComposedGeometry.xml
  filedata/unittests/gsConstantFunction.xml
  filedata/unittests/gsFunctionExpr.xml
  src/gismo.h
  src/gsAssembler/gsExpressions.h
  src/gsCore/gsBasis.h
  src/gsCore/gsComposedBasis.h
  src/gsCore/gsComposedBasis.hpp
  src/gsCore/gsComposedBasis_.cpp
  src/gsCore/gsComposedFunction.h
  src/gsCore/gsComposedFunction.hpp
  src/gsCore/gsComposedFunction_.cpp
  src/gsCore/gsComposedGeometry.h
  src/gsCore/gsComposedGeometry.hpp
  src/gsCore/gsComposedGeometry_.cpp
  src/gsCore/gsConstantBasis.h
  src/gsCore/gsConstantFunction.h
  src/gsCore/gsConstantFunction.hpp
  src/gsCore/gsConstantFunction_.cpp
  src/gsCore/gsDofMapper.h
  src/gsCore/gsForwardDeclarations.h
  src/gsCore/gsFunction.h
  src/gsCore/gsFunction.hpp
  src/gsCore/gsFunctionExpr.hpp
  src/gsCore/gsFunctionSet.h
  src/gsCore/gsGeometry.h
  src/gsIO/gsFileData.h
  src/gsIO/gsXmlGenericUtils.hpp
  src/gsIO/gsXmlInstance_.cpp
  src/gsIO/gsXmlUtils.hpp
  src/gsMSplines/gsMappedSingleBasis.h
  src/gsMSplines/gsMappedSingleSpline.h
  src/gsModeling/gsBarrierCore.hpp
  src/gsPde/gsBoundaryConditions.hpp
  unittests/gsComposedMethods_test.cpp
  unittests/gsReadFile_test.cpp
Labels: enhancement
