Repository gismo/gismo, pull requests merged in 2025-04, with the labels that each got.

#808 Fix `gsQuadrature::getAllNodes` on boundaries
  src/gsAssembler/gsQuadrature.h
Labels: bug

#798 Surface reparameterization conflict fix
  examples/surfaceReparametrization_example.cpp
  filedata/surfaces/crazySurf.xml
  optional/gsHLBFGS/gsHLBFGS.h
  optional/gsOptim/gsOptim.h
  src/gsMSplines/gsMappedBasis.h
  src/gsMSplines/gsMappedSingleBasis.h
  src/gsModeling/gsSurfaceReparameterization.h
  src/gsNurbs/gsMobiusMap.h
  src/gsOptimizer/gsGradientDescent.h
  src/gsOptimizer/gsLevenbergMarquardt.h
  src/gsOptimizer/gsOptProblem.h
  src/gsOptimizer/gsOptimizer.h
Labels: enhancement

#817 Add Zenodo DOI
  CITATION.cff
  README.md
Labels: Organization
